// Ditto SDK: 5.1.0 (Flutter package ditto_live)
//
// Document ID generation
//
// Offline devices cannot coordinate a sequence. Generate collision-free IDs
// on the device: UUID v4 (primary recommendation), a time-ordered random ID
// such as ULID, a composite object, a natural key, or an ID generated by
// Ditto (omit _id). Do not depend on the format of generated IDs.
//
// Allowed _id values: strings (recommended), objects (composite keys),
// integers/booleans/arrays (accepted, not recommended). Floats and null are
// rejected.
//
// Guide: .claude/guides/best-practices/ditto.md#document-ids

import 'dart:math';

import 'package:ditto_live/ditto_live.dart';

final _random = Random.secure();

/// ISO-8601 UTC timestamp with exactly millisecond precision, for example
/// "2026-10-08T10:30:00.123Z". Fixed precision keeps values sortable as text
/// (native Dart omits zero microseconds, so even one device would otherwise
/// mix precisions).
String utcTimestamp([DateTime? time]) {
  final utc = (time ?? DateTime.now()).toUtc();
  return DateTime.fromMillisecondsSinceEpoch(
    utc.millisecondsSinceEpoch,
    isUtc: true,
  ).toIso8601String();
}

/// Returns a random (version 4) UUID such as
/// "3f0c9a8e-5b1d-4c2a-9e7f-1a2b3c4d5e6f". A maintained package (for example,
/// `uuid` on pub.dev) works equally well.
String uuidV4() {
  final bytes = List<int>.generate(16, (_) => _random.nextInt(256));
  bytes[6] = (bytes[6] & 0x0f) | 0x40; // version 4
  bytes[8] = (bytes[8] & 0x3f) | 0x80; // RFC 4122 variant
  final hex = bytes.map((b) => b.toRadixString(16).padLeft(2, '0')).join();
  return '${hex.substring(0, 8)}-${hex.substring(8, 12)}-'
      '${hex.substring(12, 16)}-${hex.substring(16, 20)}-${hex.substring(20)}';
}

// ---------------------------------------------------------------------------
// ✅ GOOD: Collision-free IDs
// ---------------------------------------------------------------------------

/// ✅ GOOD: UUID v4. Independent devices never need to coordinate.
Future<String> createOrder(Ditto ditto, String storeId) async {
  final orderId = uuidV4();
  await ditto.store.execute(
    'INSERT INTO orders DOCUMENTS (:order)',
    arguments: {
      'order': {
        '_id': orderId,
        'storeId': storeId,
        'status': 'open',
        'createdAt': utcTimestamp(),
      },
    },
  );
  return orderId;
}

/// ✅ GOOD: Natural key. The SKU is globally unique and immutable, so two
/// devices that create the same product intentionally end up with one
/// document whose fields merge.
Future<void> upsertProductBySku(
  Ditto ditto,
  String sku,
  Map<String, dynamic> fields,
) async {
  await ditto.store.execute(
    'INSERT INTO products DOCUMENTS (:product) ON ID CONFLICT DO UPDATE_LOCAL_DIFF',
    arguments: {
      'product': {...fields, '_id': sku},
    },
  );
}

/// ✅ GOOD: Let Ditto generate the ID when nothing else needs to know it
/// before the insert, and read it back from the result.
Future<Object?> createNote(Ditto ditto, String text) async {
  final result = await ditto.store.execute(
    'INSERT INTO notes DOCUMENTS (:note)',
    arguments: {
      'note': {
        'text': text,
        'createdAt': utcTimestamp(),
      },
    },
  );
  final ids = result.mutatedDocumentIDs();
  return ids.isEmpty ? null : ids.first;
}

// ---------------------------------------------------------------------------
// ❌ BAD: Sequential and timestamp-only IDs
// ---------------------------------------------------------------------------

/// ❌ BAD: Collides when two offline devices create the 42nd order of the day.
/// After sync the two documents become one, with fields from both orders
/// mixed together.
String badSequentialId(int dailyCount) => 'order-$dailyCount';

/// ❌ BAD: Collides when two devices write within the same millisecond, and
/// device clocks are not reliable anyway.
String badTimestampId() => 'order-${DateTime.now().millisecondsSinceEpoch}';

// ---------------------------------------------------------------------------
// ✅ GOOD: Human-readable display numbers, separate from _id
// ---------------------------------------------------------------------------

/// A display label, not an identifier: uniqueness is not guaranteed across
/// devices, so never use it as _id or as a lookup key. A stable terminal code
/// that you assign avoids most duplicates; show the date alongside it.
String displayNumber(String terminalCode, int localSequence) =>
    '$terminalCode-${localSequence.toString().padLeft(4, '0')}';

Future<void> createOrderWithLabel(
  Ditto ditto, {
  required String terminalCode,
  required int localSequence,
}) async {
  await ditto.store.execute(
    'INSERT INTO orders DOCUMENTS (:order)',
    arguments: {
      'order': {
        '_id': uuidV4(),
        'displayNumber': displayNumber(terminalCode, localSequence),
        'createdAt': utcTimestamp(),
      },
    },
  );
}
